# Generated by Django 4.0.5 on 2022-06-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepCount_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_time', models.DateField()),
                ('stepCount', models.IntegerField()),
            ],
            options={
                'db_table': 'stepcountData',
            },
        ),
    ]
