# Generated by Django 4.0.5 on 2022-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepCount_Data',
            fields=[
                ('saved_time', models.DateField(primary_key=True, serialize=False)),
                ('stepCount', models.IntegerField()),
            ],
            options={
                'db_table': 'stepcountData',
            },
        ),
    ]
