# Generated by Django 4.0.5 on 2022-07-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visstep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepcount_data',
            old_name='saved_time',
            new_name='date',
        ),
    ]
